version: '3.4'

services:

  nginx-video:
    image: tirasmuturi/nginxvideo:latest
    ports:
      - '8060:80'
      - '1935:1935'
    deploy:
      mode: replicated
    command: /usr/local/nginx-streaming/sbin/nginx
    volumes:
      - /home/tiras/Docker/NginxVideo/mp4:/var/mp4s  
      - /home/tiras/Docker/NginxVideo/www:/var/www
      
